// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// dshot_600 //
// --------- //

#define dshot_600_wrap_target 0
#define dshot_600_wrap 0
#define dshot_600_pio_version 0

static const uint16_t dshot_600_program_instructions[] = {
            //     .wrap_target
    0x0000, //  0: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dshot_600_program = {
    .instructions = dshot_600_program_instructions,
    .length = 1,
    .origin = -1,
    .pio_version = dshot_600_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dshot_600_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dshot_600_wrap_target, offset + dshot_600_wrap);
    return c;
}
#endif

// --------------- //
// dshot_600_bidir //
// --------------- //

#define dshot_600_bidir_wrap_target 0
#define dshot_600_bidir_wrap 31
#define dshot_600_bidir_pio_version 0

#define dshot_600_bidir_BIDIR_START 0

static const uint16_t dshot_600_bidir_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xe081, //  1: set    pindirs, 1
    0x6050, //  2: out    y, 16
    0xe034, //  3: set    x, 20
    0x6041, //  4: out    y, 1
    0xe000, //  5: set    pins, 0
    0x006b, //  6: jmp    !y, 11
    0xb942, //  7: nop                           [25]
    0xe901, //  8: set    pins, 1                [9]
    0x00e4, //  9: jmp    !osre, 4
    0x000e, // 10: jmp    14
    0xab42, // 11: nop                           [11]
    0xf701, // 12: set    pins, 1                [23]
    0x01e4, // 13: jmp    !osre, 4               [1]
    0xe080, // 14: set    pindirs, 0
    0x20a0, // 15: wait   1 pin, 0
    0x2020, // 16: wait   0 pin, 0
    0xe023, // 17: set    x, 3
    0xe05f, // 18: set    y, 31
    0x4001, // 19: in     pins, 1
    0xa442, // 20: nop                           [4]
    0x0093, // 21: jmp    y--, 19
    0x0052, // 22: jmp    x--, 18
    0xa042, // 23: nop
    0xa042, // 24: nop
    0xa042, // 25: nop
    0xa042, // 26: nop
    0xa042, // 27: nop
    0xa042, // 28: nop
    0xa042, // 29: nop
    0xa042, // 30: nop
    0xa042, // 31: nop
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dshot_600_bidir_program = {
    .instructions = dshot_600_bidir_program_instructions,
    .length = 32,
    .origin = -1,
    .pio_version = dshot_600_bidir_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dshot_600_bidir_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dshot_600_bidir_wrap_target, offset + dshot_600_bidir_wrap);
    return c;
}
#endif

