// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// dshot_600 //
// --------- //

#define dshot_600_wrap_target 0
#define dshot_600_wrap 12
#define dshot_600_pio_version 0

static const uint16_t dshot_600_program_instructions[] = {
            //     .wrap_target
    0xff00, //  0: set    pins, 0                [31]
    0xb442, //  1: nop                           [20]
    0x80a0, //  2: pull   block
    0x6050, //  3: out    y, 16
    0x6041, //  4: out    y, 1
    0x006a, //  5: jmp    !y, 10
    0xfa01, //  6: set    pins, 1                [26]
    0xe900, //  7: set    pins, 0                [9]
    0x00e4, //  8: jmp    !osre, 4
    0x0000, //  9: jmp    0
    0xec01, // 10: set    pins, 1                [12]
    0xf600, // 11: set    pins, 0                [22]
    0x01e4, // 12: jmp    !osre, 4               [1]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dshot_600_program = {
    .instructions = dshot_600_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = dshot_600_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dshot_600_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dshot_600_wrap_target, offset + dshot_600_wrap);
    return c;
}
#endif

// --------------- //
// dshot_600_bidir //
// --------------- //

#define dshot_600_bidir_wrap_target 0
#define dshot_600_bidir_wrap 31
#define dshot_600_bidir_pio_version 0

#define dshot_600_bidir_BIDIR_START 2

static const uint16_t dshot_600_bidir_program_instructions[] = {
            //     .wrap_target
    0x0058, //  0: jmp    x--, 24
    0x8000, //  1: push   noblock
    0xe081, //  2: set    pindirs, 1
    0xe001, //  3: set    pins, 1
    0x80a0, //  4: pull   block
    0x6050, //  5: out    y, 16
    0x6041, //  6: out    y, 1
    0x006c, //  7: jmp    !y, 12
    0xfa00, //  8: set    pins, 0                [26]
    0xe901, //  9: set    pins, 1                [9]
    0x00e6, // 10: jmp    !osre, 6
    0x000f, // 11: jmp    15
    0xec00, // 12: set    pins, 0                [12]
    0xf601, // 13: set    pins, 1                [22]
    0x01e6, // 14: jmp    !osre, 6               [1]
    0xe080, // 15: set    pindirs, 0
    0xe033, // 16: set    x, 19
    0xa0eb, // 17: mov    osr, ~null
    0x01d2, // 18: jmp    pin, 18                [1]
    0xe046, // 19: set    y, 6
    0x00db, // 20: jmp    pin, 27
    0x0094, // 21: jmp    y--, 20
    0x4061, // 22: in     null, 1
    0x0000, // 23: jmp    0
    0xe14d, // 24: set    y, 13                  [1]
    0x00dc, // 25: jmp    pin, 28
    0x0014, // 26: jmp    20
    0xe146, // 27: set    y, 6                   [1]
    0x00de, // 28: jmp    pin, 30
    0x0114, // 29: jmp    20                     [1]
    0x009c, // 30: jmp    y--, 28
    0x40e1, // 31: in     osr, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dshot_600_bidir_program = {
    .instructions = dshot_600_bidir_program_instructions,
    .length = 32,
    .origin = -1,
    .pio_version = dshot_600_bidir_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dshot_600_bidir_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dshot_600_bidir_wrap_target, offset + dshot_600_bidir_wrap);
    return c;
}
#endif

